spring:
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      host: 127.0.0.1
      port: 6379
      password : rladnwo95
  datasource:
    url: jdbc:mysql://database-1.cm0qecrd80me.ap-southeast-2.rds.amazonaws.com:3306/example
    username: kimujae
    password: 5176
  jpa:
    show-sql : true
    logging.level.org.hibernate.SQL : DEBUG
    logging.level.org.hibernate.type.descriptor.sql.BasicBinder : TRACE
  main:
    allow-bean-definition-overriding : true
upload :
  path :
    upload-images : src/main/resources/static/cardAttachment
#  level:
#    root: DEBUG # Root 로거의 로깅 레벨을 INFO로 설정
#    org.springframework: DEBUG # 스프링 프레임워크 패키지의 로깅 레벨을 DEBUG로 설정
#    com.com.kujproject.kuj: TRACE # 특정 패키지(com.example.myapp)의 로깅 레벨을 TRACE로 설정
# Swagger springdoc-ui Configuration
#springdoc:
#  # swagger-ui custom path
#  springdoc.swagger-ui.path : /swagger-ui.html

#  packages-to-scan: com.kujproject.kuj.web.controller
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: /swagger-ui      # Swagger UI 경로 => localhost:8000/demo-ui.html
#    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
#  cache:
#    disabled: true
