spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/example
    username: root
    password: 5176
  jpa:
    show-sql : true
    logging.level.org.hibernate.SQL : DEBUG
    logging.level.org.hibernate.type.descriptor.sql.BasicBinder : TRACE
  main:
    allow-bean-definition-overriding : true
upload :
  path :
    upload-images : src/main/resources/static/cardAttachment
# Swagger springdoc-ui Configuration
#springdoc:
#  # swagger-ui custom path
#  springdoc.swagger-ui.path : /swagger-ui.html

#  packages-to-scan: com.kujproject.kuj.web.controller
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: /swagger-ui      # Swagger UI 경로 => localhost:8000/demo-ui.html
#    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
#  cache:
#    disabled: true
